# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgskC4ge2cBileei6pUopRaE-jAE1z59
"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Rectangle, Polygon, Circle
from ipywidgets import interact, Checkbox, Layout
from IPython.display import display

def draw_santa_house(door_open):
    """
    Rysuje świąteczny dom Mikołaja. Po otwarciu drzwi, wewnątrz pojawia się Mikołaj.
    """
    # 1. Konfiguracja figury i osi
    fig, ax = plt.subplots(figsize=(10, 8))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 8)
    ax.set_aspect('equal')
    ax.axis('off')

    # 2. Rysowanie Tła (Śnieg i Niebo)
    ground = Rectangle((0, 0), 10, 2.5, color='#F0F8FF', zorder=0)
    ax.add_patch(ground)
    sky = Rectangle((0, 2.5), 10, 5.5, color='#ADD8E6', zorder=0)
    ax.add_patch(sky)

    # 3. Rysowanie Głównego Budynku (Ściany, Dach, Komin, Okna)
    house_body = Rectangle((2.5, 2.5), 5, 3.5, color='#C0392B', zorder=1)
    ax.add_patch(house_body)

    roof_coords = np.array([[2.0, 6.0], [8.0, 6.0], [5.0, 7.5]])
    roof = Polygon(roof_coords, color='#8E44AD', zorder=2)
    ax.add_patch(roof)
    snow_on_roof = Rectangle((2.0, 6.0), 6.0, 0.2, color='white', zorder=3)
    ax.add_patch(snow_on_roof)

    chimney = Rectangle((6.5, 6.0), 0.8, 1.5, color='#7F8C8D', zorder=2)
    ax.add_patch(chimney)
    smoke1 = Circle((6.9, 8.0), 0.2, color='lightgray', alpha=0.6, zorder=3)
    ax.add_patch(smoke1)
    smoke2 = Circle((7.1, 8.3), 0.15, color='lightgray', alpha=0.5, zorder=3)
    ax.add_patch(smoke2)

    window_left = Rectangle((3.0, 3.8), 0.8, 0.8, color='#FEE140', zorder=4)
    ax.add_patch(window_left)
    window_right = Rectangle((6.2, 3.8), 0.8, 0.8, color='#FEE140', zorder=4)
    ax.add_patch(window_right)

    # Stałe współrzędne drzwi
    door_x = 4.5
    door_y = 2.5
    door_w = 1.0
    door_h = 2.0

    # 6. Interaktywne Rysowanie Drzwi i Mikołaja
    if door_open:
        # Stan "Drzwi Otwarte"

        # Rysujemy czarny otwór (tło/wnętrze)
        door_opening = Rectangle((door_x, door_y), door_w, door_h, color='black', zorder=4)
        ax.add_patch(door_opening)

        # Symulacja otwartych drzwi leżących obok
        open_door_body = Rectangle((door_x - door_w - 0.2, door_y), door_w * 0.8, door_h * 0.1, color='#8B4513', zorder=4)
        ax.add_patch(open_door_body)

        # 🎄 Rysowanie Mikołaja w Otworze Drzwiowym (jako uproszczony kształt)

        # Ciało Mikołaja (czerwony strój)
        santa_body = Rectangle((door_x + 0.15, door_y), door_w - 0.3, door_h * 0.75, color='red', zorder=5)
        ax.add_patch(santa_body)

        # Głowa Mikołaja (jasny kolor skóry)
        santa_head = Circle((door_x + 0.5, door_y + door_h * 0.75 + 0.2), 0.25, color='peachpuff', zorder=6)
        ax.add_patch(santa_head)

        # Czapka Mikołaja (biała i czerwona)
        santa_cap = Polygon([[door_x + 0.25, door_y + door_h * 0.75 + 0.45],
                            [door_x + 0.75, door_y + door_h * 0.75 + 0.45],
                            [door_x + 0.5, door_y + door_h * 0.75 + 0.8]],
                            color='red', zorder=6)
        ax.add_patch(santa_cap)

        # Wypowiedź Mikołaja
        ax.text(door_x + 0.05, door_y + 0.1, "HO! HO! HO!", color='white', fontsize=12, fontweight='bold', zorder=7)

    else:
        # Stan "Drzwi Zamknięte"
        door = Rectangle((door_x, door_y), door_w, door_h, color='#8B4513', zorder=4)
        ax.add_patch(door)

        handle = Circle((door_x + 0.9, door_y + 1.0), 0.08, color='gold', zorder=5)
        ax.add_patch(handle)
        wreath = Circle((door_x + 0.5, door_y + 1.7), 0.3, color='darkgreen', linewidth=3, edgecolor='red', fill=False, zorder=5)
        ax.add_patch(wreath)

    # 7. Choinka i Tytuł
    tree_coords = np.array([[1.0, 2.5], [2.0, 2.5], [1.5, 4.0]])
    tree = Polygon(tree_coords, color='darkgreen', zorder=1)
    ax.add_patch(tree)
    star = Polygon([[1.5, 4.3], [1.4, 4.1], [1.6, 4.1]], color='yellow', zorder=2)
    ax.add_patch(star)

    ax.set_title("Interaktywny Dom Świętego Mikołaja 🎅", fontsize=16, color='darkblue')

    plt.show()

# 8. Tworzenie interaktywnego widżetu
print("Użyj pola poniżej, aby OTWORZYĆ drzwi i zobaczyć Mikołaja:")
interact(draw_santa_house,
         door_open=Checkbox(
             value=False,
             description='Otwórz Drzwi',
             layout=Layout(width='auto')
         )
        );